server:
  port: 38643

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: tinysnow;

# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: tinysnow-hope-one-day-everyone-can-be-fabulous-and-happy-including-ancielin
    # 令牌有效期（默认30分钟）
    expireTime: 30
    # 令牌签发者
    issuer: tinysnow